version: '3'
services:
  master:
    build: ../cluster-image
    ports:
      - "8108:8108"
      - "1234:1234"
    entrypoint: "./pdb-cluster master 8108 Y"
    hostname: "master"
    security_opt:
      - seccomp:unconfined
    links:
      - worker_1
      - worker_2
  worker_1:
    build: ../cluster-image
    ports:
      - "8109:8109"
      - "1235:1235"
    entrypoint: "./pdb-server 1 2048 master:8108 worker_1:8109"
    hostname: "worker_1"
    security_opt:
      - seccomp:unconfined
  worker_2:
     build: ../cluster-image
     ports:
       - "8110:8110"
       - "1236:1236"
     entrypoint: "./pdb-server 1 2048 master:8108 worker_2:8110"
     hostname: "worker_2"
     security_opt:
       - seccomp:unconfined
  frontend:
     build: ../frontend-image
     entrypoint: "/bin/bash -c 'make test; chmod -R 777 .'"
     hostname: "frontend"
     volumes:
       - "${PDB_ROOT}:/pdb"
     security_opt:
       - seccomp:unconfined
     links:
       - master